name: Build APK

on: [push]

# Permisos necesarios para subir el APK
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Usa la versión actualizada

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libtinfo5 cmake libffi-dev libssl-dev libxml2-dev libxslt1-dev

      - name: Install Buildozer
        run: pip install buildozer

      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses

      - name: Generate APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Versión actualizada
        with:
          name: app-debug
          path: bin/*.apk  # Verifica que la ruta sea correcta
