name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build APK
      uses: mreichelt/p4a-build-action@v1
      with:
        requirements: "python3,kivy,requests"
        arch: "arm64-v8a"
        android_api: 28
        package_name: "org.example.iotdashboard"
        app_name: "IoT Dashboard"
    - uses: actions/upload-artifact@v3
      with:
        name: apk
        path: dist/
