name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-22.04  # Versión específica con más espacio
    timeout-minutes: 120    # 2 horas de timeout
    
    env:
      BUILDDOZER_ANDROID_SKIP_NO_SPACE_CHECK: 1
      PIP_CACHE_DIR: ~/.cache/pip
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Free disk space
      run: |
        # Limpieza agresiva para liberar espacio
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /usr/local/lib/android/sdk/build-tools
        sudo apt clean
        sudo apt autoremove -y
        df -h

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libxml2-dev libxslt-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade Cython==0.29.36 virtualenv
        pip install buildozer==1.5.0

    - name: Configure Android NDK
      run: |
        wget --tries=5 --waitretry=30 --no-check-certificate https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip
        mkdir -p ~/.buildozer/android/platform
        mv android-ndk-r25b ~/.buildozer/android/platform/
        echo "ANDROID_NDK_HOME=~/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
        echo "PATH=$PATH:~/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV

    - name: Cache Buildozer dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Build APK
      run: |
        # Limpiar builds anteriores
        buildozer android clean || true
        
        # Construir APK
        buildozer -v android debug
        
        # Si falla, mostrar el error
        if [ $? -ne 0 ]; then
          [ -f buildozer.log ] && tail -100 buildozer.log
          exit 1
        fi

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: iot-dashboard-apk
        path: bin/*.apk
        retention-days: 1

    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-failure-logs
        path: |
          buildozer.log
          .buildozer/**/*.log
