name: Build APK
on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 \
          cmake libffi-dev libssl-dev

    - name: Install Buildozer
      run: pip install buildozer

    - name: Configure Buildozer
      run: |
        buildozer init
        # Actualiza el archivo buildozer.spec
        echo "[app]" > buildozer.spec
        echo "title = IoT Dashboard" >> buildozer.spec
        echo "package.name = iotdashboard" >> buildozer.spec
        echo "package.domain = org.example" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,ttf,json" >> buildozer.spec
        echo "version = 1.0.0" >> buildozer.spec
        echo "requirements = python3,kivy,requests,openssl,pyopenssl,certifi,android" >> buildozer.spec
        echo "orientation = portrait" >> buildozer.spec
        echo "osx.python_version = 3" >> buildozer.spec
        echo "android.api = 34" >> buildozer.spec
        echo "android.ndk = 25b" >> buildozer.spec
        echo "android.permissions = INTERNET" >> buildozer.spec
        echo "android.arch = arm64-v8a" >> buildozer.spec

    - name: Build APK
      run: buildozer -v android debug
      timeout-minutes: 40  # La primera compilación puede tardar

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: iot-dashboard-apk
        path: bin/*.apk
